# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os.path
import urllib.request
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtCore import *
import winshell


class Setup_Launcher(QThread):
    signalWorker = pyqtSignal(str)

    def __init__(self, mainwindow, parent=None):
        super().__init__()
        self.mainwindow = mainwindow

    def run(self):
        self.mainwindow.progressBar.show()
        self.mainwindow.label_4.show()
        self.mainwindow.line_26.show()
        self.mainwindow.line_27.show()
        self.mainwindow.line_28.show()
        self.mainwindow.line_29.show()
        self.mainwindow.line_30.show()
        self.mainwindow.line_31.show()
        self.mainwindow.line_5.close()
        direct = self.mainwindow.textEdit.toPlainText()
        self.mainwindow.progressBar.setValue(0)

        ddos_img = urllib.request.urlopen(
            "https://drive.google.com/u/0/uc?id=1GKzyIO67QlCo_pWHA59x3wYaZI_AHd-m&export=download").read()
        with open(f"{direct}/PyProgramsLauncher/Image/DDOS.png", "wb") as f:
            f.write(bytes(ddos_img))
            print("Фото установлено")

        self.mainwindow.progressBar.setValue(2)
        self.mainwindow.progressBar.setValue(6)

        vk_img = urllib.request.urlopen(
            "https://drive.google.com/u/0/uc?id=1S0A7gzC5GJvUcLM9uJevKdwmHA_D2al4&export=download").read()
        with open(f"{direct}/PyProgramsLauncher/Image/VkBrut.png", "wb") as f:
            f.write(bytes(vk_img))
            print("Фото установлено")

        self.mainwindow.progressBar.setValue(10)
        self.mainwindow.progressBar.setValue(15)
        self.mainwindow.progressBar.setValue(20)

        ip_img = urllib.request.urlopen(
            "https://drive.google.com/u/0/uc?id=1xwzL8Vb-U0LZ_UQY_KhmIClX3ttlqvdo&export=download").read()
        with open(f"{direct}/PyProgramsLauncher/Image/IP Hack.png", "wb") as f:
            f.write(bytes(ip_img))
            print("Фото установлено")

        self.mainwindow.progressBar.setValue(21)
        self.mainwindow.progressBar.setValue(25)
        self.mainwindow.progressBar.setValue(29)

        Py_img = urllib.request.urlopen(
            "https://drive.google.com/u/0/uc?id=1HlGKgEAo0aMwybLxxHl7Nt0sgEMMBEEH&export=download").read()
        with open(f"{direct}/PyProgramsLauncher/Image/Py.png", "wb") as f:
            f.write(bytes(Py_img))
            print("Фото установлено")

        self.mainwindow.progressBar.setValue(34)
        self.mainwindow.progressBar.setValue(40)

        bot_img = urllib.request.urlopen(
            "https://drive.google.com/u/0/uc?id=1EJ5zMyyyvUHlZKCsxsOSv5v5GariCwcG&export=download").read()
        with open(f"{direct}/PyProgramsLauncher/Image/бот.png", "wb") as f:
            f.write(bytes(bot_img))
            print("Фото установлено")

        self.mainwindow.progressBar.setValue(46)
        self.mainwindow.progressBar.setValue(52)
        self.mainwindow.progressBar.setValue(57)

        in_bot_img_1 = urllib.request.urlopen(
            "https://drive.google.com/u/0/uc?id=12Y_KVX6kmIpKyrciNTOBk5iCsdFYSQlL&export=download").read()
        with open(f"{direct}/PyProgramsLauncher/Image/Bot/Back.png", "wb") as f:
            f.write(bytes(in_bot_img_1))
            print("Фото установлено")

        self.mainwindow.progressBar.setValue(65)
        self.mainwindow.progressBar.setValue(72)
        self.mainwindow.progressBar.setValue(81)

        in_bot_img_2 = urllib.request.urlopen(
            "https://drive.google.com/u/0/uc?id=12Y_KVX6kmIpKyrciNTOBk5iCsdFYSQlL&export=download").read()
        with open(f"{direct}/PyProgramsLauncher/Image/Bot/бот.png", "wb") as f:
            f.write(bytes(in_bot_img_2))
            print("Фото установлено")

        self.mainwindow.progressBar.setValue(84)
        self.mainwindow.progressBar.setValue(99)

        SetupLaunch = urllib.request.urlopen(
            "https://drive.google.com/u/0/uc?id=1acU_VZ7JxfKXuCL1o5pQUHV5DHQnEFXW&export=download&confirm=t&uuid"
            "=61132503-a702-4753-8710-d8093b23fad2").read()
        with open(f"{direct}/PyProgramsLauncher/Py_programs_launcher.exe", "wb") as f:
            f.write(bytes(SetupLaunch))
            print("Фото установлено")


        Check = self.mainwindow.checkBox.isChecked()

        if Check:
            Launcher = f"{direct}/PyProgramsLauncher/Py_programs_launcher.exe"
            # print(Launcher)
            winshell.CreateShortcut(os.path.join(winshell.desktop(), "Py_programs_launcher.lnk"),
                                    Launcher,
                                    Icon=(Launcher, 0),
                                    Description='Py_programs_launcher')
        else:
            print("Без ярлыка")

        self.mainwindow.progressBar.setValue(100)

        self.mainwindow.progressBar.close()
        self.mainwindow.label_4.close()
        self.mainwindow.line_26.close()
        self.mainwindow.line_27.close()
        self.mainwindow.line_28.close()
        self.mainwindow.line_29.close()
        self.mainwindow.line_30.close()
        self.mainwindow.line_31.close()
        self.mainwindow.line_5.show()
        self.mainwindow.line_6.show()
        self.mainwindow.line_7.show()
        self.mainwindow.line_8.show()
        self.mainwindow.line_9.show()
        self.mainwindow.pushButton.show()
        self.mainwindow.line_21.show()
        self.mainwindow.line_22.show()
        self.mainwindow.line_23.show()
        self.mainwindow.line_24.show()
        self.mainwindow.pushButton.setText('Закрыть')
        self.mainwindow.checkBox.setGeometry(QtCore.QRect(360, 121, 231, 29))
        self.mainwindow.line_19.show()
        self.mainwindow.line_18.show()
        self.mainwindow.line_17.show()
        self.mainwindow.label_3.setGeometry(QtCore.QRect(323, 122, 51, 29))
        self.mainwindow.label_3.show()
        self.mainwindow.checkBox.show()
        self.mainwindow.checkBox.setText('Установка завершена')
        self.mainwindow.label_3.raise_()


class Ui_MainWindow(object):
    def __init__(self):
        self.start_thread = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 308)
        MainWindow.setMinimumSize(QtCore.QSize(693, 308))
        MainWindow.setMaximumSize(QtCore.QSize(693, 308))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 311))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("1.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 241, 241))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Icon6.png"))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 260, 241, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 25, 241, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 32, 21, 237))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(260, 32, 21, 237))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(270, 125, 51, 21))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(310, 30, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("color: rgb(0, 222, 248);\n"
                                       "background-color: rgb(0, 0, 0);")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(310, 30, 360, 3))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(310, 70, 360, 3))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(310, 30, 3, 42))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(670, 30, 3, 42))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_20 = QtWidgets.QFrame(self.centralwidget)
        self.line_20.setGeometry(QtCore.QRect(270, 220, 251, 21))
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.line_25 = QtWidgets.QFrame(self.centralwidget)
        self.line_25.setGeometry(QtCore.QRect(270, 220, 91, 21))
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(360, 220, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("color: rgb(0, 227, 251);\n"
                                       "")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 220, 261, 41))
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.line_26 = QtWidgets.QFrame(self.centralwidget)
        self.line_26.setGeometry(QtCore.QRect(360, 220, 3, 37))
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.line_27 = QtWidgets.QFrame(self.centralwidget)
        self.line_27.setGeometry(QtCore.QRect(360, 209, 261, 20))
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.line_28 = QtWidgets.QFrame(self.centralwidget)
        self.line_28.setGeometry(QtCore.QRect(360, 245, 261, 31))
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.line_29 = QtWidgets.QFrame(self.centralwidget)
        self.line_29.setGeometry(QtCore.QRect(610, 218, 20, 41))
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(630, 70, 20, 131))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_30 = QtWidgets.QFrame(self.centralwidget)
        self.line_30.setGeometry(QtCore.QRect(630, 70, 20, 171))
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.line_31 = QtWidgets.QFrame(self.centralwidget)
        self.line_31.setGeometry(QtCore.QRect(620, 230, 21, 20))
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.line_32 = QtWidgets.QFrame(self.centralwidget)
        self.line_32.setGeometry(QtCore.QRect(270, 120, 21, 31))
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(330, 70, 20, 29))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(293, 88, 48, 21))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(282, 97, 20, 39))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(522, 201, 147, 59))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 0);color: rgb(0, 222, 248);")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(322, 121, 269, 58))
        self.textBrowser_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                         "color: rgb(0, 222, 248);")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(323, 145, 184, 29))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                    "color: rgb(0, 224, 250);")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 145, 81, 34))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 189, 221);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.line_36 = QtWidgets.QFrame(self.centralwidget)
        self.line_36.setGeometry(QtCore.QRect(321, 143, 269, 3))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.line_36.setFont(font)
        self.line_36.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.line_37 = QtWidgets.QFrame(self.centralwidget)
        self.line_37.setGeometry(QtCore.QRect(507, 144, 4, 33))
        self.line_37.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(330, 121, 261, 29))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: rgb(0, 215, 240);\n"
                                    "background-color: rgb(0, 0, 0);")
        self.checkBox.setObjectName("checkBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(323, 121, 20, 29))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(591, 124, 21, 21))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(603, 133, 16, 66))
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_21 = QtWidgets.QFrame(self.centralwidget)
        self.line_21.setGeometry(QtCore.QRect(520, 199, 3, 61))
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.line_23 = QtWidgets.QFrame(self.centralwidget)
        self.line_23.setGeometry(QtCore.QRect(520, 199, 151, 3))
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.line_22 = QtWidgets.QFrame(self.centralwidget)
        self.line_22.setGeometry(QtCore.QRect(670, 200, 3, 61))
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.line_24 = QtWidgets.QFrame(self.centralwidget)
        self.line_24.setGeometry(QtCore.QRect(520, 260, 152, 3))
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.line_33 = QtWidgets.QFrame(self.centralwidget)
        self.line_33.setGeometry(QtCore.QRect(320, 120, 3, 59))
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.line_34 = QtWidgets.QFrame(self.centralwidget)
        self.line_34.setGeometry(QtCore.QRect(590, 120, 3, 59))
        self.line_34.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.line_35 = QtWidgets.QFrame(self.centralwidget)
        self.line_35.setGeometry(QtCore.QRect(320, 171, 271, 13))
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(320, 120, 3, 30))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(590, 120, 3, 30))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(320, 150, 272, 3))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(320, 120, 271, 3))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(321, 122, 270, 29))
        self.textBrowser_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                         "color: rgb(0, 222, 248);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label.raise_()
        self.label_2.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.textBrowser.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        self.line_12.raise_()
        self.line_13.raise_()
        self.line_20.raise_()
        self.line_25.raise_()
        self.label_4.raise_()
        self.progressBar.raise_()
        self.line_26.raise_()
        self.line_27.raise_()
        self.line_28.raise_()
        self.line_29.raise_()
        self.line_17.raise_()
        self.line_30.raise_()
        self.line_31.raise_()
        self.line_32.raise_()
        self.line_16.raise_()
        self.line_14.raise_()
        self.line_15.raise_()
        self.pushButton.raise_()
        self.line_37.raise_()
        self.label_3.raise_()
        self.checkBox.raise_()
        self.line_18.raise_()
        self.line_19.raise_()
        self.line_21.raise_()
        self.line_23.raise_()
        self.line_22.raise_()
        self.line_24.raise_()
        self.line_33.raise_()
        self.line_34.raise_()
        self.line_8.raise_()
        self.textBrowser_2.raise_()
        self.line_7.raise_()
        self.line_6.raise_()
        self.textBrowser_3.raise_()
        self.line_35.raise_()
        self.pushButton_2.raise_()
        self.textEdit.raise_()
        self.line_36.raise_()
        self.line_9.raise_()
        self.line_33.close()
        self.pushButton_2.close()
        self.textBrowser_2.close()
        self.textBrowser_3.close()
        self.textEdit.close()
        self.line_37.close()
        self.line_34.close()
        self.line_8.close()
        self.line_36.close()
        self.line_8.show()
        self.progressBar.close()
        self.line_26.close()
        self.line_27.close()
        self.line_28.close()
        self.line_29.close()
        self.label_4.close()

        MainWindow.setCentralWidget(self.centralwidget)
        self.line_35.close()
        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.line_25.show)
        self.pushButton.clicked.connect(self.line_15.show)
        self.pushButton.clicked.connect(self.line_14.show)
        self.pushButton.clicked.connect(self.line_16.show)
        self.pushButton.clicked.connect(self.line_32.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.start_thread = Setup_Launcher(mainwindow=self)
        self.pushButton.setText('Продолжить')
        self.pushButton_2.clicked.connect(lambda: self.open_files())
        self.pushButton.clicked.connect(lambda: self.all_in_one())

    def all_in_one(self):
        if self.pushButton.text() == 'Продолжить':
            self.setup_launch()
        elif self.pushButton.text() == 'Установить':
            self.start_setup_launch()
        else:
            self.close_installer()

    def open_files(self):
        import os
        open1 = QFileDialog.getExistingDirectory(None, 'Выберите папку', os.getenv('HOME'))
        self.textEdit.setText(open1)

    def start_setup_launch(self):
        import os
        from PyQt5.QtWidgets import QMessageBox
        if self.textEdit.toPlainText() == "":

            error = QMessageBox()
            error.setWindowTitle('Вы не указали директорию для установки')
            error.setText("Вы не указали директорию для установки")
            error.setIcon(QMessageBox.Warning)
            error.setInformativeText("Пожалуйста укажите директорию для установки")
            error.setStandardButtons(QMessageBox.Ok)
            error.exec_()
        else:
            text = self.textEdit.toPlainText()
            direct = os.path.exists(text)
            if direct:
                self.textEdit.close()
                self.textBrowser_3.close()
                self.textBrowser_2.close()
                self.line_6.close()
                self.line_7.close()
                self.line_8.close()
                self.line_9.close()
                self.pushButton.close()
                self.checkBox.close()
                self.pushButton_2.close()
                self.label_3.close()
                self.line_35.close()
                self.line_33.close()
                self.line_34.close()
                self.line_19.close()
                self.line_18.close()
                self.line_36.close()
                self.line_21.close()
                self.line_22.close()
                self.line_23.close()
                self.line_24.close()
                self.start_thread.start()
                try:
                    os.mkdir(f'{self.textEdit.toPlainText()}/PyProgramsLauncher')
                except:
                    print("Папка существует")

                try:
                    os.mkdir(f'{self.textEdit.toPlainText()}/PyProgramsLauncher/Image')
                except:
                    print("Папка существует")

                try:
                    os.mkdir(f'{self.textEdit.toPlainText()}/PyProgramsLauncher/Programs')
                except:
                    print("Папка существует")

                try:
                    os.mkdir(f'{self.textEdit.toPlainText()}/PyProgramsLauncher/Image/bot')
                except:
                    print("Папка существует")

            else:
                error = QMessageBox()
                error.setWindowTitle('Неверная директория установки')
                error.setText("Вы указали недействительную директорию для установки")
                error.setIcon(QMessageBox.Warning)
                error.setInformativeText("Пожалуйста измените её на действительную")
                error.setStandardButtons(QMessageBox.Ok)
                error.exec_()

    def close_installer(self):
        import sys
        sys.exit()

    def setup_launch(self):
        self.textBrowser_3.show()
        self.line_34.show()
        self.line_35.show()
        self.line_33.show()
        self.textEdit.show()
        self.pushButton_2.show()
        self.line_35.raise_()
        self.line_36.show()
        self.pushButton.setText('Установить')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Py_Programs_Launcher installer"))
        self.textBrowser.setHtml(_translate("MainWindow",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
                                            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Установщик Py_Programs_Launcher</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "Установить"))
        self.textBrowser_3.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9.75pt; font-weight:400; font-style:normal;\">\n"
                                              "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Выберите директорию для установки:</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Открыть"))
        self.checkBox.setText(_translate("MainWindow", "Создать ярлык на рабочем столе"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.textBrowser_2.setHtml(_translate("MainWindow",
                                              "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                              "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                              "p, li { white-space: pre-wrap; }\n"
                                              "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9.75pt; font-weight:400; font-style:normal;\">\n"
                                              "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Программа успешно установилась</span></p></body></html>"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
